dist: trusty
language: python
sudo: false
notifications:
  email: false
python:
- '2.7'
install:
- pip install -r server/python/requirements/dev.txt
- nvm install node
- nvm use node
- npm install --prefix client/knowledge_base_search
script: flake8 &&
        npm run test-unit --prefix client/knowledge_base_search &&
        npm run build --prefix client/knowledge_base_search &&
        python -m pytest &&
        phantomjs --version &&
        npm run test-integration --prefix client/knowledge_base_search
before_install:
- openssl aes-256-cbc -K $encrypted_22e51202b5e7_key -iv $encrypted_22e51202b5e7_iv
  -in .env.staging.enc -out .env.staging -d
- cp .env.staging .env
